import React from 'react'
import Navbar  from '../components/Navbar'
import Footer from '../components/Footer'
import Head from 'next/head'

const Layout = ({children, title, bgColor}) => {
  bgColor = bgColor || 'bg-teal-600';
  return (
    <div className=" font-mono ">
        <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        </Head>
        <div className="flex flex-col min-h-screen ">
        <Navbar />
        <main className={`flex px-5 h-full w-full justify-center grow ${bgColor}`}>

            {children}

        </main>
        <Footer/>
        </div>
    </div>
  )
}

export default Layout